@startuml

class Application
class Certificate
class Domain
class Event
class Login
class Participant
class Process
class Registration
class User

Domain --{ Process
Registration }-- Process
Registration }-- Application
Application }--{ "uses" Certificate
Application "customer of" --{ "owned by" Participant
User }-- Participant
Participant --{ "owns" Certificate
Participant --{ Event
Participant --{ Login

@enduml