@startuml

class Application
class Certificate
class Domain
class Event
class Login
class Participant
class Process
class Registration
class User

Domain -left-{ Process
Registration }-right- Process
Registration }-- Application
Application }--{ "uses" Certificate
Application }-- "owned by" Participant
Application "customer of" }-- Participant
Participant --{ "owns" Certificate
Participant --{ Event
Participant -right-{ Login
Participant --{ User
Login "0..1" -- User

@enduml